export const storyPrompts = [
    "The knight ventured into the shadowy forest, guided only by whispers.",
    "A forgotten city emerged from the depths of the ocean.",
    "The ancient castle gates creaked open after 500 years of silence.",
    "A mysterious map led them to a place that didn’t exist on any chart.",
    "A lone traveler found a magical key buried under a dying tree.",
    "The moon turned crimson, and the world began to change.",
    "A dragon guarded a treasure that no one wanted to claim.",
    "In the heart of the desert lay a door with no walls.",
    "The stars flickered, sending a message only the chosen could understand.",
    "Shadows came alive as the village clock struck midnight.",
    "A letter with no sender arrived, containing secrets no one should know.",
    "The library basement had a room that wasn’t on any blueprints.",
    "Every mirror in the house reflected something slightly different.",
    "A stranger handed them an envelope and whispered, 'Don’t open this.'",
    "Footsteps echoed through the abandoned mansion, though it was empty.",
    "A train ticket for a journey to a place that didn’t exist.",
    "The painting on the wall changed every time someone looked away.",
    "A locked box appeared at their doorstep with a ticking sound inside.",
    "Someone—or something—was moving things around the house at night.",
    "The lighthouse light shone on something hidden beneath the waves.",
    "The ship’s AI started singing a lullaby no one had ever heard.",
    "A black hole appeared in the middle of their kitchen.",
    "The last human on Earth received a signal from space.",
    "Robots ruled the world, but one machine discovered it could dream.",
    "A portal to another dimension opened, but only animals could enter.",
    "The stars began rearranging themselves into words.",
    "A time traveler returned home to find everything slightly… wrong.",
    "The planet’s surface was covered in ancient, glowing symbols.",
    "The spaceship’s crew found a message written 1,000 years in the future.",
    "A meteor crashed to Earth carrying something alive… and aware.",
    "The town’s fountain began flowing with liquid gold overnight.",
    "Every time they turned a page in the book, their life changed slightly.",
    "The forest refused to let anyone leave after sundown.",
    "Birds began delivering handwritten letters to everyone in the city.",
    "A new constellation appeared in the sky, and it matched someone’s face.",
    "The bakery’s bread could heal any sickness—but at a cost.",
    "A bridge appeared overnight, leading to a place no one had ever seen.",
    "Rain fell in colors no one had ever seen before.",
    "A door appeared in the middle of the road, and it was unlocked.",
    "The river whispered names that no one had spoken in centuries.",
    "The clock tower rang thirteen times at midnight.",
    "A child claimed they had been to a place where time stopped.",
    "Everyone in town dreamed the same dream on the same night.",
    "A shop sold wishes, but no one knew the price until it was too late.",
    "The clouds formed words that predicted the future.",
    "Music began playing from a house that had been empty for years.",
    "A flower bloomed where no plant had grown for centuries.",
    "The forest path led them to a place that should not exist.",
    "Statues began moving when no one was watching.",
    "A ghostly figure appeared in the town square every full moon.",
    "Snow fell in only one house on the entire street.",
    "The diary wrote itself with events from the future.",
    "Every step they took left glowing footprints behind.",
    "The shadows on the walls moved on their own.",
    "A carnival appeared overnight and vanished at dawn.",
    "The stars blinked out one by one, leaving only darkness.",
    "A girl found a golden feather that could grant wishes.",
    "The forest animals began speaking in riddles.",
    "A forgotten language started appearing on every surface.",
    "The fire in the hearth whispered secrets to anyone who listened.",
    "The moon split into two, and the world began to change.",
    "A boy found a map that led to the end of the world.",
    "The ocean revealed a staircase leading deep underwater.",
    "The wind carried voices of people long forgotten.",
    "An ancient statue turned its head and looked at them.",
    "A pair of shoes took their wearer to places they had never been.",
    "A candle burned endlessly without ever melting.",
    "The well in the center of town granted answers, but not truth.",
    "The stars fell to Earth, turning into stones of immense power.",
    "A single tree stood in the field, and it was covered in keys.",
    "The forest floor glowed with symbols that no one could decipher.",
    "A stranger claimed they knew how the world would end.",
    "Dreams began merging with reality, and no one noticed.",
    "A mirror showed reflections of events that hadn’t happened yet.",
    "The windmill began turning, though no wind was blowing.",
    "A clock appeared in the sky, counting down to something unknown.",
    "The lantern led them forward, though no one was holding it.",
    "A rift appeared in the middle of town, leading into darkness.",
    "The castle walls whispered stories of their builders.",
    "A book appeared on their doorstep, and every page was blank.",
    "The old man claimed he could see into everyone’s future.",
    "The cat returned home wearing a necklace it had never owned.",
    "The sun stopped moving in the sky, frozen at dawn.",
    "A family portrait changed to include someone no one recognized.",
    "A violin began playing itself in the empty attic.",
    "The rain only fell on one house in the entire town.",
    "People began finding feathers of an unknown bird in their homes.",
    "The train station led to platforms that did not exist.",
    "A garden grew overnight with plants no one could identify.",
    "The stars aligned into a message no one could read.",
    "The wind carried the faint sound of someone calling their name.",
    "A staircase appeared in the middle of the field, leading nowhere.",
    "The candle’s flame burned blue whenever someone lied nearby.",
    "The clock tower began counting backward.",
    "The mountains rumbled as though something inside was trying to escape.",
    "A voice spoke from the bottom of the well.",
    "The forest grew denser every time someone tried to leave.",
    "They found a locked door in their house that had never been there before.",
    "The lake began freezing in perfect circles.",
    "A child claimed the stars had spoken to them.",
    "The birds stopped singing, and the forest fell silent.",
    "A golden ring was found in the river, inscribed with a name no one knew."
  ];
  